#!/bin/bash

# LinkOps-Arise Security Audit Script
# Generated by GP-Copilot Security Platform
# Date: September 25, 2025

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}LinkOps-Arise Security Audit${NC}"
echo -e "${GREEN}========================================${NC}"

# Set paths
PROJECT_ROOT="/home/jimmie/linkops-industries/James-OS/james-copilots/GP-copilot/GP-PROJECTS/LinkOps-Arise"
GP_COPILOT_ROOT="/home/jimmie/linkops-industries/James-OS/james-copilots/GP-copilot"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
AUDIT_DIR="${PROJECT_ROOT}/GP-copilot/audits/${TIMESTAMP}"

# Create audit directory
mkdir -p "${AUDIT_DIR}"

echo -e "\n${YELLOW}Starting security scans...${NC}\n"

# Run Trivy scan
echo -e "${YELLOW}[1/5] Running Trivy scan...${NC}"
PYTHONPATH="${GP_COPILOT_ROOT}" python3 "${GP_COPILOT_ROOT}/GP-CONSULTING-AGENTS/scanners/trivy_scanner.py" "${PROJECT_ROOT}" || true

# Run Bandit scan
echo -e "${YELLOW}[2/5] Running Bandit scan...${NC}"
PYTHONPATH="${GP_COPILOT_ROOT}" python3 "${GP_COPILOT_ROOT}/GP-CONSULTING-AGENTS/scanners/bandit_scanner.py" "${PROJECT_ROOT}" || true

# Run Gitleaks scan
echo -e "${YELLOW}[3/5] Running Gitleaks scan...${NC}"
PYTHONPATH="${GP_COPILOT_ROOT}" python3 "${GP_COPILOT_ROOT}/GP-CONSULTING-AGENTS/scanners/gitleaks_scanner.py" "${PROJECT_ROOT}" || true

# Run Semgrep scan
echo -e "${YELLOW}[4/5] Running Semgrep scan...${NC}"
PYTHONPATH="${GP_COPILOT_ROOT}" python3 "${GP_COPILOT_ROOT}/GP-CONSULTING-AGENTS/scanners/semgrep_scanner.py" "${PROJECT_ROOT}" || true

# Run TFSec scan
echo -e "${YELLOW}[5/5] Running TFSec scan...${NC}"
PYTHONPATH="${GP_COPILOT_ROOT}" python3 "${GP_COPILOT_ROOT}/GP-CONSULTING-AGENTS/scanners/tfsec_scanner.py" "${PROJECT_ROOT}" || true

# Copy scan results
echo -e "\n${YELLOW}Collecting scan results...${NC}"
cp "${GP_COPILOT_ROOT}/GP-DATA/active/scans/"*.json "${AUDIT_DIR}/" 2>/dev/null || true

# Generate summary
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Audit Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "Results saved to: ${AUDIT_DIR}"
echo -e "\nFor detailed analysis, review:"
echo -e "  - ${PROJECT_ROOT}/GP-copilot/COMPREHENSIVE_SECURITY_AUDIT_REPORT.md"
echo -e "  - ${PROJECT_ROOT}/GP-copilot/AUDIT_SUMMARY.md"

# Count issues
TFSEC_ISSUES=$(find "${AUDIT_DIR}" -name "*tfsec*.json" -exec grep -c '"findings"' {} \; 2>/dev/null | head -1 || echo "0")

if [ "${TFSEC_ISSUES}" -gt "0" ]; then
    echo -e "\n${RED}⚠ Security issues detected! Review scan results.${NC}"
else
    echo -e "\n${GREEN}✅ No critical security issues detected.${NC}"
fi