server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - argocd.local
    tls:
    - secretName: argocd-server-tls
      hosts:
      - argocd.local

configs:
  secret:
    argocdServerAdminPassword: "$2a$10$mYaJ8KqQqQqQqQqQqQqQqO"

rbac:
  create: true

repoServer:
  serviceAccount:
    create: true

applicationSet:
  enabled: true 
